# Generated by Django 5.0.7 on 2024-07-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout_zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='workout/profile_pictures')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_zones.hall')),
            ],
        ),
    ]
